### ISSUE TITLE
Xdebug with FrankenPHP doesn't work with step debugging mode.

### ISSUE THREAD

**Issue by Thomthomars** [dunglas/frankenphp-drupal#15]
Hi
I create this issue to get some help.
I've migrate my project from a regular config with a container apache and php_fpm.
In that config my container php_fpm expose port 9010, so after few configuration PHPSTORM trigger when script execution is detected.
From the new configuration my php project is derectly mount in caddy container, and php_fpm doesn't exist.
I install Xdebug in container and expose port 9010.

When I run a cli command from container PHP stop on break point and allow to step debugging. However when I navigate on my website, PHPSTORM isn't able to catch script execution.

I don't know how can I enable step debugging outside container.

Tel me if you need some detail.

thx

**Comment by dunglas** [comment]
Fixed by https://github.com/dunglas/frankenphp/pull/214

**Comment by Thomthomars** [comment]
Yeah, work as design in [symfony-docker & Xdebug](https://github.com/dunglas/symfony-docker/blob/main/docs/xdebug.md#debugging-with-xdebug-and-phpstorm)
